# Generated by Django 2.0 on 2018-02-16 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RentAnItem', '0004_item_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itype',
        ),
        migrations.AddField(
            model_name='item',
            name='itype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RentAnItem.category'),
        ),
    ]
