# Generated by Django 2.0 on 2018-02-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentAnItem', '0005_auto_20180216_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itype',
        ),
    ]
